# Generated by Django 4.2 on 2024-11-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('sales_price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='image/product/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_fk', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('previous_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Product_Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_fk', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('supplier_fk', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
            options={
                'db_table': 'product_supplier',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_fk',
            field=models.ForeignKey(db_column='tax_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_fk',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='base.unit'),
        ),
    ]
