# Generated by Django 4.2 on 2024-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_fk',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax_fk',
            new_name='tax_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_fk',
            new_name='unit_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product/'),
        ),
    ]
