# Generated by Django 4.2.14 on 2024-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_supplier',
            old_name='product_fk',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product_supplier',
            old_name='supplier_fk',
            new_name='supplier_id',
        ),
        migrations.AddField(
            model_name='product_supplier',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
    ]
